### ISSUE TITLE
Create cleaned WHO dataset

### ISSUE THREAD

**Issue by ShylaTatum** [ShylaTatum/Group-Project-1#2]
Some specific tasks related to cleaning are dependent on working group decisions for what we want to include in our final dataset. This list will evolve as we answer those questions together.

- [x] Create a working Jupyter notebook file to test cleaning
- [x] Add necessary data CSV files for filling in any gaps
- [x] Add imports for CSV files
- [x] Filter dataset for list of chosen countries
- [x] Merge in external datasets for country name and ICD code description
- [x] Create columns for age groups
- [x] Create final cleaned DataFrame with chosen list of columns

**Comment by d3rp3tt3** [comment]
Some updates - these are also in the pull request #21. 

_____
This workbook goes to the root of the repo and:

* Imports CSVs and creates DataFrames
* Merges DataFrames together
* Adds new grouped columns for "death buckets"
* Drops unessential columns
* Renames columns
* Reorganizes column orders
* Exports the cleaned data to a new CSV
* The death groups, column names, and order of columns needs to be discussed with the team.
____

I've added two new cells to the workbook to test that the new cleaned CSV was created properly.

Create a new DataFrame by importing the CSV.
Display the first 5 rows of the DataFrame.
_____

I've added a new cell to show the lengths of the pre-filtered and new filtered DataFrames. This helps us show how much data we are working with in the new frame vs. the old. 

> There are 1,023,260 rows in the full dataset and 227,831 rows in the filtered DataFrame. Result: The filtered DataFrame is 795,429 shorter.
