### ISSUE TITLE
Add ICD Codes for use in mapping for our DataFrames

### ISSUE THREAD

**Issue by ShylaTatum** [ShylaTatum/Group-Project-1#4]
Get a subset of data to use as a key for ICD Codes.

**Comment by d3rp3tt3** [comment]
After doing some data exploration, I see we're going to have to include more than one set of ICD codes sets. The documentation calls this out. 

<img width="601" alt="Screenshot 2024-08-07 at 4 34 00 PM" src="https://github.com/user-attachments/assets/ce9e27f3-6c36-41da-b550-67cd0862acad">

I originally saw the simplified codes only (ICD10 101). I then saw the complex codes for ICD10 103 and 104. 

```# Read WHO morbidity data and create DataFrame
df_mort = pd.read_csv('../source_data/morticd10_part5_rev')

# Get distinct values for ICD 10 types
distinct_list_values = df_mort['List'].unique()
print(distinct_list_values)

 -- output -- 
[101 103 104]```

**Comment by d3rp3tt3** [comment]
Update - the filtered list of countries we're reporting on all use ICD10 104. Therefore, we can use the standard latest code set. I'll remove the unnecessary code list and update the mapping in the exploratory Jupyter notebook.
